# Generated by Django 4.0.1 on 2022-02-11 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_articles_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='thumb',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='articles'),
            preserve_default=False,
        ),
    ]
