# Generated by Django 4.0.1 on 2022-02-12 00:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_alter_articles_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='thumb',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='categories'),
            preserve_default=False,
        ),
    ]
